### ISSUE TITLE
Hide display for Casters if no target

### ISSUE THREAD

**Issue by sparkiespaark** [herotc/hero-rotation#243] opened 2018-08-20 18:05 UTC
Hey can you please make it so it doesn't show the display for Mages and Boomkin unless you have a target/combat, I am sure it's like it for others too. But I know for Rogue it doesn't show until you have a target. I did try myself but I have no idea what to change/add or where.

**Comment by Cilraaz** [comment] 2019-02-28 17:13
Duplicate of #236

**Closed by Cilraaz** 2019-02-28 17:13 UTC
Labels: Duplicate
