### ISSUE TITLE
Slice N Dice Global CD OPtion

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#975] opened 2023-07-01 16:26 UTC
### What feature would you like to have added?

Please add Slice n Dice to the options panel to allow us to move it to the GCD window or a separate window like you have for other classes.  I know the importance of Slice n Dice but there are sometimes I want to press another finisher due to mob health or pvp scenario and the fact that nothing else shows up as an option until Slice n Dice is up, is extremely frustrating.

**Comment by Cilraaz** [comment] 2023-10-08 23:28
Duplicate of #722

**Closed as completed by Cilraaz** 2023-10-08 23:28 UTC
Labels: Duplicate
