### ISSUE TITLE
[Bug]: [Survival Hunter] Pooling & Not Suggesting Kill Command/Flanking Strike

### ISSUE THREAD

**Issue by Exsol-bit** [herotc/hero-rotation#1126] opened 2024-10-05 06:56 UTC
### What version of HeroRotation are you using?

11.0.2.52

### What version of HeroLib are you using?

11.0.2.1.17

### What version of HeroDBC are you using?

11.0.2.04

### What is the issue?

On ST fights (Dummy's and raid/dungeon bosses) Pooling Focus is suggested when there are abilities available (screenshot attached).

At the time of the SS Kill Command was available with 2 charges, Explosive Shot & enough focus to cast Raptor Strike.

![Screenshot 2024-10-05 164238](https://github.com/user-attachments/assets/6d466752-decc-4197-bca8-05a8f98b3209)
![Screenshot 2024-10-05 164246](https://github.com/user-attachments/assets/0ddfcb59-02a5-491f-9bfc-2160788ea1db)

Similar issues occur with the rotation seemly ignoring Kill Command (to buff the next ability) and Flanking Strike, hr debug was showing "Raptor Strike sentst 6" - Serpent Sting was present on the mob.
![Screenshot 2024-10-05 164733](https://github.com/user-attachments/assets/9ec82b8b-13f2-4208-901d-df937e11a297)

Talent loadout - C8PAFBU0uAhOaNI6RqWjIx917NGYgtxox2AysFsNzYbGzMzwMmZYmZMzMmZMAAAAAAAAAAAAAAoZYMjZmZmZGzwYYmhxwMmBb

AOE seems to function perfectly with HR correctly alternating between Kill Command and 'spender' (Wildfire Bomb/Flanking Strike etc), I only notice the above on ST.

### Icon Behavior

None

**Comment by Cilraaz** [comment] 2024-10-15 01:43
Duplicate of #1112

**Comment by Exsol-bit** [comment] 2024-10-15 04:44
Hey Cilraaz, the issues above doesn't appear to be the same as https://github.com/herotc/hero-rotation/issues/1112, as I was always in melee range.

I tested the new commit and the same issues as above are occurring (it did resolve the Aspect of the Eagle issue).

This is the HR debug output leading up to the attached screenshot.

> [Hero Rotation] Pooling Focus 
> [Hero Rotation] wildfire_bomb sentst 2 
> [Hero Rotation] spearhead sentst 6 
> [Hero Rotation] Pooling Focus 
> [Hero Rotation] wildfire_bomb sentst 2 
> [Hero Rotation] Pooling Focus 
> [Hero Rotation] wildfire_bomb sentst 2 
> [Hero Rotation] Pooling Focus 
> [Hero Rotation] wildfire_bomb sentst 2

![Screenshot 2024-10-15 154944](https://github.com/user-attachments/assets/4f78f687-202f-4e5e-a7e9-32c87068e75d)

**Comment by Cilraaz** [comment] 2024-10-15 13:22
I tested this morning and am unable to replicate the issue, though my Hunter is only 70. If your UI shows spell IDs, can you please let me know the spell ID of Kill Command, just in case one of your hero talents changes its ID for some reason.

**Comment by Exsol-bit** [comment] 2024-10-16 06:48
> I tested this morning and am unable to replicate the issue, though my Hunter is only 70. If your UI shows spell IDs, can you please let me know the spell ID of Kill Command, just in case one of your hero talents changes its ID for some reason.

Kill Command ID - 259489

It occurs after about 30 seconds of combat, the initial opener seems to function _correctly_ (still not pressing Flanking Strike as soon as I'd expect, but that might just be the APL opener).

Unsure if this is helpful or not, but this is the opener output and below is a quick sim opener from raidbots (I understand if there will always be discrepancies between HR/APL and what Raidbots shows).

> [Hero Rotation] wildfire_bomb sentst 2  (While standing at range)
> [Hero Rotation] mongoose_bite precombat 6  (When walking into melee range)
> [Hero Rotation] wildfire_bomb sentst 2 
> [Hero Rotation] explosive_shot sentst 18  (This is when Coordinated Assault is suggested as OffGCD)
> [Hero Rotation] Mongoose Bite sentst 8 
> [Hero Rotation] kill_command sentst 24 
> [Hero Rotation] wildfire_bomb sentst 2 
> [Hero Rotation] spearhead sentst 6 
> [Hero Rotation] kill_command sentst 24 
> [Hero Rotation] Mongoose Bite sentst 8 
> [Hero Rotation] flanking_strike sentst 12 
> [Hero Rotation] Mongoose Bite sentst 8 
> [Hero Rotation] kill_command sentst 26 
> [Hero Rotation] explosive_shot sentst 18 
> [Hero Rotation] kill_command sentst 26 
> [Hero Rotation] explosive_shot sentst 18 
> [Hero Rotation] kill_command sentst 26 
> [Hero Rotation] explosive_shot sentst 18 



![Screenshot 2024-10-16 174338](https://github.com/user-attachments/assets/40e39d76-788c-4a86-8c0a-3bc2dc6fa7b4)

**Comment by Cilraaz** [comment] 2024-10-16 13:48
There's no opener in the APL, per se.

I checked a few things and it appears that the "buff" from Relentless Primal Ferocity is actually a hidden buff. That was likely contributing to the issue. I'm trying a change where instead of looking for this buff, which will never be found, we instead look for the Coordinated Assault buff while the Relentless Primal Ferocity talent is selected. This is now allowing the highest priority Kill Command suggestion to occur, which might pull everything else in line.

This change is included in commit https://github.com/herotc/hero-rotation/commit/6178661151f6fa245aa864b7b6d0e1de3e263d01

Please let me know if this helps.

**Comment by Exsol-bit** [comment] 2024-10-16 23:27
There wasn't any noticeable difference with commit [https://github.com/herotc/hero-rotation/commit/6178661151f6fa245aa864b7b6d0e1de3e263d01](6178661)

Within 40seconds of combat, it was essentially stuck on 'Pooling' only flicking to Wildfire Bomb when it came off cooldown.

 In the picture you can see 2 stacks of Kill Command, Flanking Strike and max fury to use on Mongoose Bite/Raptor Strike, all of which should be suggested.

![Screenshot 2024-10-17 090833](https://github.com/user-attachments/assets/db7361f1-164b-46cc-8f95-77203bd2cda8)

**Comment by Exsol-bit** [comment] 2024-10-16 23:37
The cleave coding works perfectly (sentcleave), rotating abilities flawlessly never missing Flanking Strike, and using Kill Command correctly.

I'm not sure if there's a glaring difference between these two that can easily identify the issue/difference.

```
>   -- flanking_strike,if=buff.tip_of_the_spear.stack=2|buff.tip_of_the_spear.stack=1
>   if S.FlankingStrike:IsCastable() and (Player:BuffStack(S.TipoftheSpearBuff) == 2 or Player:BuffStack(S.TipoftheSpearBuff) == 1) then
>     if Cast(S.FlankingStrike, nil, nil, not Target:IsSpellInRange(S.FlankingStrike)) then return "flanking_strike sentcleave 12"; end
>   end
```

```
  -- flanking_strike,if=buff.tip_of_the_spear.stack=2|buff.tip_of_the_spear.stack=1
  if S.FlankingStrike:IsReady() and (Player:BuffStack(S.TipoftheSpearBuff) == 2 or Player:BuffStack(S.TipoftheSpearBuff) == 1) then
    if Cast(S.FlankingStrike, nil, nil, not Target:IsSpellInRange(S.FlankingStrike)) then return "flanking_strike sentst 12"; end
  end
```

I noticed that moving out of melee range did correct the Flank Strike suggestion for ST. The below HR output was me simply moving in and out of melee, when outside of melee it would suggest flanking strike (correctly).

> [Hero Rotation] kill_command sentst 24 
> [Hero Rotation] Raptor Strike sentst 8 
> [Hero Rotation] flanking_strike sentst 12 
> [Hero Rotation] Raptor Strike sentst 8 
> [Hero Rotation] flanking_strike sentst 12 
> [Hero Rotation] Raptor Strike sentst 8 
> [Hero Rotation] flanking_strike sentst 12 
> [Hero Rotation] Raptor Strike sentst 8 
> [Hero Rotation] flanking_strike sentst 12 
> [Hero Rotation] Raptor Strike sentst 8 

I also noticed something similar when moving in and out of melee when 'pooling' was shown:

> [Hero Rotation] Pooling Focus 
> [Hero Rotation] Raptor Strike sentst 8 
> [Hero Rotation] Pooling Focus 
> [Hero Rotation] kill_shot sentst 22 
> [Hero Rotation] explosive_shot sentst 18

I tested without Coordinated Assault (and the two sub talents) just in case it was something funky with the Relentless Primal Ferocity.

Let me know if there's anything else I can test/show to assist.

**Comment by Cilraaz** [comment] 2024-10-17 02:21
Try commit https://github.com/herotc/hero-rotation/commit/ed3bb58c0bd94bffe1dacfaece8cace8fb518377

I found a few issues, but primarily the fact that Survival has a different spell ID for Serpent Sting than BM/MM. This was causing the "Raptor Strike sentst 8" line to be over-prioritized.

**Comment by Exsol-bit** [comment] 2024-10-17 03:27
Fixed! Works great, crazy how something so small could cause so many issues.

My only other request, if at all possible and not a lot of effort is to move Spearhead (1min CD) to OffGCD or add a toggle.

Either way, stamp a big ol 'resolved' on this bug report :)

**Comment by Cilraaz** [comment] 2024-10-17 03:32
OffGCD option added in commit https://github.com/herotc/hero-rotation/commit/0111867bff563ea585a5d4eb2a039059d129437c

I'll go ahead and mark this resolved and close it. Let us know if you run into anything else, and thank you for all the troubleshooting help!

**Closed as completed by Cilraaz** 2024-10-17 03:32 UTC
Labels: Bug, Fixed
