### ISSUE TITLE
[Bug]: Demonology profile does not load automatically

### ISSUE THREAD

**Issue by Vavalgia** [herotc/hero-rotation#1052] opened 2024-04-28 12:27 UTC
### What version of HeroRotation are you using?

10.2.6.13

### What version of HeroLib are you using?

10.2.6.02

### What version of HeroDBC are you using?

10.2.6.01

### What is the issue?

When playing on my demo warlock the addon does not load until i type /reload in the chat bar. this is the only character it does this on

### Icon Behavior

None

**Comment by Cilraaz** [comment] 2024-04-28 15:20
Unable to replicate. Profile loads as expected upon login.

**Comment by Vavalgia** [comment] 2024-04-28 15:48
Is there anything else I can share to help out with the bug. It works fine on my other characters.

**Comment by Vavalgia** [comment] 2024-04-29 09:31
I've figured out that it is the addon Better wardrobe that is causing this problem. however i have reset, reinstalled better wardrobe and the error still occurs. but again only on this character and no other.

**Comment by QueensideRook** [comment] 2024-04-30 10:09
Came to report a similar strange behavior, when I log in to my Affliction warlock, I get the following lua error:

```
Message: Interface/AddOns/HeroRotation_Warlock/Demonology.lua:67: attempt to compare two nil values
Time: Tue Apr 30 02:56:41 2024
Count: 1
Stack: Interface/AddOns/HeroRotation_Warlock/Demonology.lua:67: attempt to compare two nil values
[string "=[C]"]: ?
[string "@Interface/AddOns/HeroRotation_Warlock/Demonology.lua"]:67: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:395: in function `PulseInit'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:303: in function <Interface/AddOns/HeroRotation/Main.lua:300>

Locals: (*temporary) = <function> defined =[C]:-1
```

After seeing your issue was caused by BetterWardrobe, I disabled it and the issue disappeared. After relogging, the same lua error above appears when logging in, accompanied by the Hero Rotation message for not finding the spec. As mentioned, /reloadui also causes the spec to load properly.

I'm personally not terribly bothered by the issue and just wanted to bring it to developer attention. I don't know how BetterWardrobe could possibly be conflicting with Hero Rotation in such a weirdly specific way, but it does sound like it's either an issue with BetterWardrobe or an unresolvable (if minor) conflict between the two addons.

**Comment by Cilraaz** [comment] 2024-04-30 11:46
It's almost as if the addon is trying to pull your equipment list and is getting nothing in return (or you're not wearing any trinkets?). That error is actually when the item level of both trinkets is being compared. I'm still unable to replicate the issue, but I've added some failsafe code that will assume an item level of 0 when none is found. At worst, trinkets will be suggested in the "wrong" order when using two on-use trinkets. This should be an extremely minor loss of dps in the worst possible scenario.

The hopeful fix is included in commit https://github.com/herotc/hero-rotation/commit/52a8cd21b39a9cc4570c5e6cdc30a287658bb6dd

**Comment by QueensideRook** [comment] 2024-04-30 12:02
I am currently wearing level boost trinkets, which notably have issues with ilvl comparison in Pawn, so that may be contributing?

Edit: you might be able to replicate the error using heirloom trinkets?

**Comment by Cilraaz** [comment] 2024-04-30 12:12
It might be a contributing factor. I don't understand why it would work after a /reload, though. In any case, the failsafe code should resolve that issue. Essentially, any time the addon can't determine the item level of a trinket, it just substitutes a zero. The value is only used in a comparison where the APL tries to determine which on-use trinket should be used first when wearing two on-use trinkets. Currently, this math is performed regardless of whether two on-use trinkets are in use. I'm going to add code to change that, though.

**Comment by QueensideRook** [comment] 2024-04-30 13:05
Tested commit 1b26a78 and I can confirm the lua error no longer appears for me, Demonology spec loads upon login without reloading, trinkets remain the same, BetterWardrobe is loaded.

**Comment by Cilraaz** [comment] 2024-04-30 13:17
Awesome! Thanks for reporting back!

**Closed as completed by Cilraaz** 2024-04-30 13:17 UTC
Labels: Bug, Fixed
