### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by behemot011** [herotc/hero-rotation#937] opened 2023-05-04 14:50 UTC
### What version of HeroRotation are you using?

10.1.0.01

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

Lua error while using the rotation with shadowpriest

Message: Interface/AddOns/HeroRotation/Commons.lua:75: attempt to call local 'Condition' (a nil value)
Time: Thu May  4 10:48:14 2023
Count: 152
Stack: Interface/AddOns/HeroRotation/Commons.lua:75: attempt to call local 'Condition' (a nil value)
[string "@Interface/AddOns/HeroRotation/Commons.lua"]:75: in function `CastCycle'
[string "@Interface/AddOns/HeroRotation_Priest/Shadow.lua"]:511: in function <Interface/AddOns/HeroRotation_Priest/Shadow.lua:488>
[string "@Interface/AddOns/HeroRotation_Priest/Shadow.lua"]:569: in function <Interface/AddOns/HeroRotation_Priest/Shadow.lua:515>
[string "@Interface/AddOns/HeroRotation_Priest/Shadow.lua"]:639: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:455: in function <Interface/AddOns/HeroRotation/Main.lua:433>

Locals: Object = <table> {
 LastCastTime = 1851665.646000
 LastHitTime = 1851665.646000
 LastAppliedOnPlayerTime = 1851665.646000
 LastRemovedFromPlayerTime = 1851672.662000
 SpellName = "Mindgames"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 1851665.605000
 SpellID = 375901
}
Enemies = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
Condition = nil
OutofRange = false
OffGCD = nil
DisplayStyle = "Suggested"
(*temporary) = nil
(*temporary) = <table> {
 UnitExists = true
 UnitName = "Cleave Training Dummy"
 UnitNPCID = 198594
 UnitID = "target"
 UseCache = true
 UnitCanBeAttacked = true
 UnitGUID = "Creature-0-3024-2444-2578-198594-000052FF6F"
}
(*temporary) = "attempt to call local 'Condition' (a nil value)"
Target = <table> {
 UnitExists = true
 UnitName = "Cleave Training Dummy"
 UnitNPCID = 198594
 UnitID = "target"
 UseCache = true
 UnitCanBeAttacked = true
 UnitGUID = "Creature-0-3024-2444-2578-198594-000052FF6F"
}
HR = <table> {
 CastPooling = <function> defined @Interface/AddOns/HeroRotation/Core.lua:173
 MaxQueuedCasts = 3
 CmdHandler = <function> defined @Interface/AddOns/HeroRotation/Core.lua:273
 PulseInit = <function> defined @Interface/AddOns/HeroRotation/Main.lua:365
 GetTexture = <function> defined @Interface/AddOns/HeroRotation/Core.lua:46
 APLInits = <table> {
 }
 LastUnitCycledTime = 1851552.678000
 CastSuggested = <function> defined @Interface/AddOns/HeroRotation/Core.lua:246
 CastQueuePooling = <function> defined @Interface/AddOns/HeroRotation/Core.lua:201
 CastAnnotated = <function> defined @Interface/AddOns/HeroRotation/Core.lua:164
 PulsePreInit = <function> defined @Interface/AddOns/HeroRotation/Main.lua:308
 LeftIconFrame = HeroRotation_LeftIconFrame {
 }
 CastRightSuggested = <function> defined @Interface/AddOns/HeroRotation/Core.lua:259
 GUISettings = <table> {
 }
 LastUnitCycled = <table> {
 }
 ChangePulseTimer = <function> defined @Interface/AddOns/HeroRotation/Main.lua:479
 AoEON = <function> defined @Interface/AddOns/HeroRotation/Core.lua:358
 NameplateIconFrame = HeroRotation_NameplateIconFrame {
 }
 CreateBackdrop = <function> defined @Interface/AddOns/HeroRotation/UI.lua:68
 ToggleIconFrame = HeroRotation_ToggleIconFrame {
 }
 RightSuggestedIconFrame = HeroRotation_RightSuggestedIconFrame {
 }
 Commons = <table> {
 }
 Print = <function> defined @Interface/AddOns/HeroRotation/Core.lua:31
 ResetIcons = <function> defined @Interface/AddOns/HeroRotation/UI.lua:37
 Cast = <function> defined @Interface/AddOns/HeroRotation/Core.lua:135
 Pulse = <function> defined @Interface/AddOns/HeroRotation/Main.lua:433
 Timer = <table> {
 }
 MainFrame = HeroRotation_MainFrame {
 }
 Locked = <function> defined @Interface/AddOns/HeroRotation/Core.lua:369
 Nameplate = <table> {
 }
 CastLeftCommon = <function> defined @Interface/AddOns/HeroRotation/Core.lua:224
 Ready = <function> defined @Interface/AddOns/HeroRotation/Main.lua:468
 APLs = <table> {
 }
 SuggestedIconFrame = HeroRotation_SuggestedIconFrame {
 }
 CastLeftOffset = 1
 SmallIconFrame = HeroRotation_SmallIconFrame {
 }
 SetAPL = <function> defined @Interface/AddOns/HeroRotation/Core.l

### Icon Behavior

None

**Comment by Cilraaz** [comment] 2023-05-04 14:54
Duplicate of issue #936 

Fixed in commit https://github.com/herotc/hero-rotation/commit/387ec4f506c7c9c785f8f6c4ce8e526b7fd9c416

**Closed as completed by Cilraaz** 2023-05-04 14:54 UTC
Labels: Duplicate
