### ISSUE TITLE
[7.3.5] Warlock Demonology - Glyphs vs Rotation

### ISSUE THREAD

**Issue by Nazeth** [herotc/hero-rotation#173] opened 2018-06-19 22:05 UTC
I'm using Glyph of Wrathguard and rotation asking me to use "Summon Felguard" all the times when i have summoned Wrathguard. Probably the same problem will be with their special abilities - Felstorm and Wrathstorm and other minions and abilities changed by glyphs.

**Comment by aethys256** [comment] 2018-07-26 18:56
Duplicate of https://github.com/herotc/hero-rotation/issues/166
Closing since BfA is around the corner and the discussion is no longer relevant.

**Closed by aethys256** 2018-07-26 18:56 UTC
