### ISSUE TITLE
Not Showing Keybinds Correctly

### ISSUE THREAD

**Issue by esc-scripts** [herotc/hero-rotation#749] opened 2021-04-06 17:30 UTC
Here is an example for Pyroblast. Some keys it shows, others not at all.

![image](https://user-images.githubusercontent.com/73078719/113753606-2cac0100-9706-11eb-9b07-6666ba279891.png)

**Comment by Cilraaz** [comment] 2021-04-06 17:38
Duplicate of #747. Please update to HeroLib version 9.0.5.04.

**Comment by esc-scripts** [comment] 2021-04-06 18:11
I have updated to 9.0.5.04. and switched to Frost as the spec is finished and now the keys show the wrong binds.

![image](https://user-images.githubusercontent.com/73078719/113758499-de016580-970b-11eb-96df-39df01a07d74.png)

**Comment by Cilraaz** [comment] 2021-04-06 18:22
What hotbar addon are you using?

**Comment by esc-scripts** [comment] 2021-04-06 18:25
Bartender4. I am using that on my pally too and hero is working flawlessly there.

**Comment by esc-scripts** [comment] 2021-04-06 18:51
Have fixed myself. Please close this.

**Closed as completed** 2021-04-06 18:52 UTC
Labels: Duplicate
