### ISSUE TITLE
[UI] Keybinds Inconsistent

### ISSUE THREAD

**Issue by Colorado4Wheeler** [herotc/hero-rotation#563] opened 2020-10-14 17:37 UTC
I know things are WIP, but I'm wondering if while the Shadowlands stuff is being dialed in if the key binds showing up is one of the things impacted.  With the update I get one icon showing a key bind (when targeting before combat) and then no others show from that point forward.  I do use Bartender, if that is of any help.  

The version I'm testing it on is 9.0.1.02.

**Comment by Kutikuti** [comment] 2020-10-17 18:14
Keybind label with bartender is a bit buggy right now, i'll look at it

**Comment by Synderryn** [comment] 2020-10-20 02:50
Keybinds haven't been showing up for me at all. I've been maining a BM Hunter, if that helps.

**Comment by mhunk** [comment] 2020-10-20 13:49
> Keybinds haven't been showing up for me at all. I've been maining a BM Hunter, if that helps.

same here as sub rogue

**Comment by shadofall** [comment] 2020-11-08 15:11
dont know the cause. but if you go in to blizzards key bind interface and set the bartender keybinds there for bar 1 instead of using BT's /KB command. KB's will start showing up on the rotation, some reason atleast for me only impacts bar1 as my keybinds from another bar worked fine

**Comment by Cilraaz** [comment] 2021-11-09 02:28
The keybind code has been re-written since this issue was last updated. Closing this issue. If this is still a problem, please feel free to open a new issue.

**Closed by Cilraaz** 2021-11-09 02:28 UTC
Labels: Fixed
