### ISSUE TITLE
Request: Add option to take summon infernal off GCD

### ISSUE THREAD

**Issue by gac21116** [herotc/hero-rotation#551] opened 2020-05-23 18:05 UTC
Right now, summon infneral appears as a main icon and there doesn't appear to be a way to change that and I ddidn't see it as one of the options of abilities to take off of gcd so that it would appear as a smaller icon in top left

**Comment by Cilraaz** [comment] 2020-05-23 20:42
Duplicate of issue #550

**Closed by Cilraaz** 2020-05-23 20:42 UTC
Labels: Duplicate
