### ISSUE TITLE
Slice N Dice

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#818] opened 2022-01-26 21:01 UTC
Please give an option for the player to move slice and dice to the off GCD section instead of the main window, it throws me off when I'm opening up in PvP. I know my opener but it messes with the mind somehow when you see that huge icon on there. please this is my third request for this option. everything else seems customizable, all I ask is to give me the option to decide when I want to use it. Thanks.

**Comment by Cilraaz** [comment] 2023-10-08 23:25
Duplicate of #722

**Closed as completed by Cilraaz** 2023-10-08 23:25 UTC
Labels: Duplicate
