### ISSUE TITLE
Fire Mage - Lua Errors

### ISSUE THREAD

**Issue by Furyenn** [herotc/hero-rotation#230] opened 2018-08-05 05:22 UTC
After casting the first recommended fire mage ability (Pyroblast) the addon generates the following Lua Error and does not recommend another spell.

Message: Interface\AddOns\HeroRotation_Mage\Fire.lua:352: attempt to index global 'firestarter' (a nil value)
Time: Sun Aug  5 01:19:34 2018
Count: 154
Stack: Interface\AddOns\HeroRotation_Mage\Fire.lua:352: attempt to index global 'firestarter' (a nil value)
[C]: ?
Interface\AddOns\HeroRotation_Mage\Fire.lua:352: in function `?'
Interface\AddOns\HeroRotation\Main.lua:432: in function <Interface\AddOns\HeroRotation\Main.lua:410>

**Comment by ghr74** [comment] 2018-08-05 05:26
Duplicate of #202 .

**Closed by ghr74** 2018-08-05 05:26 UTC
