### ISSUE TITLE
feral rotation keeps regrowth icon up, while resting in stormwind

### ISSUE THREAD

**Issue by antisocialian** [herotc/hero-rotation#271] opened 2018-09-13 00:31 UTC
I understand the need to precast a HOT so that it's going while combat starts(at least for raids), but I like a minimal UI, and having the icon sitting in the middle of the screen telling me to cast regrowth in town cause it isn't on me is annoying. After casting it, it leaves the smaller icons of cat form and prowl instead. Once the regrowth wears off, it comes back and hides the cat form and prowl icons.

I find it best to keep the rotation icons int he middle of the screen so i'm looking at it and my feet(don't stand in the fire) and without a way to hide the rotation when i'm not targeting anything or while rested really needs to be an option. I don't need to see rotation help in town or without a target.

I currently have the 8.0.1.07(and tried the alpha 8.0.1.07-1-gd060193-alpha as well).

Feral isn't the only spec that I've noticed having suggestions when I'm not needing or wanting them, please look into adding options to hide while resting and another for no target.

**Comment by Cilraaz** [comment] 2019-02-28 17:14
Duplicate of #236

**Closed by Cilraaz** 2019-02-28 17:14 UTC
Labels: Duplicate
