### ISSUE TITLE
[Unholy DK] getting errors everytime unholy frenzy shows up

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#475] opened 2019-08-14 09:14 UTC
getting errors everytime unholy frenzy shows up, can you guys fix this please?

**Comment by azzi1103** [comment] 2019-08-14 09:15
Also put Bloodelf racial in main icon if you can on unholy spec?

**Comment by Cilraaz** [comment] 2019-08-14 14:43
I'm unable to reproduce any error with Unholy Frenzy. What error are you receiving?

**Comment by azzi1103** [comment] 2019-08-14 17:29
I will screenshot it when I go on my dk again. Error always comes when unholy frenzy gets recommended

**Comment by Cilraaz** [comment] 2019-08-14 17:34
I ran a few cycles and had it suggested multiple times without a problem. It might be a talent/azerite/trinket related issue causing it to happen for you and not for me. When you post the screenshot, could you also include your talent build (simple number format like 1231231 is fine), trinkets equipped when the error happens, azerite essences equipped when the error happens, and if you have the azerite trait Magus of the Dead. Thanks!

**Comment by azzi1103** [comment] 2019-08-15 10:02
https://i.gyazo.com/87a51d06b2ab9758145e76d730405845.png

**Comment by Cilraaz** [comment] 2019-08-15 12:21
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/94f678f29a97f9b1175fe4dfd045cead5855df9b

There was a typo.

**Closed by Cilraaz** 2019-08-15 12:21 UTC
Labels: Fixed
