### ISSUE TITLE
Error for Rotations: DragonBall Z POOL icon during Rotation? 

### ISSUE THREAD

**Issue by WorgenPaws** [herotc/hero-rotation#213] opened 2018-07-29 03:17 UTC
Noticed on Monk, Druid and Hunter so far. When suggesting a rotation, everything will seem fine (all the abilities will come as they are supposed to and show up) but then randomly it shows an image that looks its from Dragonball Z and says POOL. Its a bright yellow icon. What does this mean and is it an error? It can throw off a rotation if you are learning a new class.

**Comment by WorgenPaws** [comment] 2018-07-29 03:42
![wowscrnshot_072818_233558](https://user-images.githubusercontent.com/41846575/43362753-e0520a90-92bf-11e8-9a30-0d46da326685.jpg)

Here is the error as it happens on my Hunter.

**Comment by ghr74** [comment] 2018-07-29 03:48
Duplicate of #143 .

**Closed by ghr74** 2018-07-29 03:48 UTC

**Comment by ghr74** [comment] 2018-07-29 03:59
To reference your comment on the issue linked above, furthermore this AddOn only supports max level characters. According to your screenshot, your character is not max level.
In addition, we currently don't accept error reports for specs marked as outdated on this table:
https://github.com/herotc/hero-rotation#supported-rotations
