### ISSUE TITLE
Combat or target toggle option Frost Mage

### ISSUE THREAD

**Issue by qsauce** [herotc/hero-rotation#181] opened 2018-07-18 14:51 UTC
Is it possible to either set the addon to only show rotation buttons either on hostile target or on combat. As at the moment im getting an icon showing at all times other than flight and im sure I only used to get an icon showing when in combat other than that the addon was completely hidden until the new update. This is when using my frost mage, not sure if its the rotation addon files or something else doing it.

Is this something im missing or was the option removed? Currently using the Alpha version
Edit have been looking at the code and the frost mage module is written in a totally different way to the rest the others seem to have an in and out of combat toggle that hides the icons however the frost one has a precombat  function that seems to be the issue (not that im up with lua or any other coding but from what i can guess thats the problem)

**Comment by ghr74** [comment] 2019-05-03 05:37
Frost mage now has a target check on the offensive opener spell, hiding of all icons would be a duplicate of https://github.com/herotc/hero-rotation/issues/128 so I'll close this one.

**Closed by ghr74** 2019-05-03 05:37 UTC
Labels: Bug
