### ISSUE TITLE
[warlock] spell keybind indication

### ISSUE THREAD

**Issue by Juliacare** [herotc/hero-rotation#176] opened 2018-06-23 10:46 UTC
https://imgur.com/a/hVBuSsc

It tells you to summon imp using the Grimoire imp keybind.

Similair issue to the armor set issue from a month or two ago.

**Comment by AlexanderKenny** [comment] 2018-06-23 19:10
Most likely going to need some actual debug info to go on since I don't have a warlock. But for starters the suggested bind is just the spell itself correct? (Not a macro etc?). Additionally you're sure it's not just suggesting Grimoire ya?

**Comment by ghr74** [comment] 2018-06-23 19:12
Caused by both having the same icon, I'll probably add a config menu for keybind overrides come BfA. Will close this when it's in, I guess.

**Comment by Juliacare** [comment] 2018-06-23 19:15
@ghr74 is correct. I had the same issue, like suggested in the orginal post, with armor sets on my mage where the armor set had the same icon as ice lance. This caused the addon to suggest to use the armor set's keybind instead of frostbolt's keybind since they had the same icon. It's now doing the same with the grimoire. As by example of the picture you can see one is summon the imp (perma pet) and one is summon the imp through the grimoire as a cooldown usage. Yet the have the same binding which leads back to the grimoire. No macro's or anything was used, they're just spells taken raw from the spellbook.

**Comment by Kutikuti** [comment] 2020-12-22 13:46
Cleanup

**Closed by Kutikuti** 2020-12-22 13:46 UTC
Labels: Enhancement
