### ISSUE TITLE
Arcane Mage errors

### ISSUE THREAD

**Issue by ghost** [herotc/hero-rotation#613] opened 2020-11-26 22:10 UTC
Any time I start casting a spell the addon starts throwing errors at a high rate. It worked well yesterday.

`104x HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "@HeroLib\Class\Unit\Aura.lua"]:32: in function <HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@HeroLib\Class\Unit\Aura.lua"]:148: in function `DebuffRemains'
[string "@HeroLib\Class\Unit\Aura.lua"]:159: in function `DebuffUp'
[string "@HeroLib\Class\Unit\Aura.lua"]:164: in function `DebuffDown'
[string "@HeroLib\Class\Unit\Aura.lua"]:132: in function `DebuffStack'
[string "@HeroRotation_Mage\Arcane.lua"]:607: in function <HeroRotation_Mage\Arcane.lua:561>
[string "@HeroRotation_Mage\Arcane.lua"]:907: in function `?'
[string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>

Locals:
self = <table> {
 UnitCanBeAttacked = true
 IsSpellInActionRange = <function> defined @HeroLib\Events\Action.lua:426
 IsItemInActionRange = <function> defined @HeroLib\Events\Action.lua:416
 UnitID = "target"
 UseCache = true
 UnitExists = true
 IsActionInRange = <function> defined @HeroLib\Class\Unit\Target\Range.lua:23
 UnitGUID = "Creature-0-3781-2222-139-172581-0002BFD2B2"
 UnitName = "Slimelet"
 UnitNPCID = 172581
}
ThisSpell = nil
Filter = "HARMFUL|PLAYER"
Full = nil
GUID = "Creature-0-3781-2222-139-172581-0002BFD2B2"
UnitID = "target"
(*temporary) = <table> {
 UnitCanBeAttacked = true
 IsSpellInActionRange = <function> defined @HeroLib\Events\Action.lua:426
 IsItemInActionRange = <function> defined @HeroLib\Events\Action.lua:416
 UnitID = "target"
 UseCache = true
 UnitExists = true
 IsActionInRange = <function> defined @HeroLib\Class\Unit\Target\Range.lua:23
 UnitGUID = "Creature-0-3781-2222-139-172581-0002BFD2B2"
 UnitName = "Slimelet"
 UnitNPCID = 172581
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'ThisSpell' (a nil value)"
UnitAura = <function> defined =[C]:-1
`

**Comment by Cilraaz** [comment] 2020-11-26 22:12
Duplicate of issue #611

**Closed as completed by Cilraaz** 2020-11-26 22:12 UTC
Labels: Duplicate
