### ISSUE TITLE
[Bug]: Feral druid LUA error

### ISSUE THREAD

**Issue by stormerdoom** [herotc/hero-rotation#992] opened 2023-10-12 02:38 UTC
### What version of HeroRotation are you using?

10.1.7.10

### What version of HeroLib are you using?

10.1.7.03

### What version of HeroDBC are you using?

10.1.7.01

### What is the issue?

Playing as a feral druid I am getting a LUA error. Character is level 61 if that matters.

409x HeroRotation_Druid/Feral.lua:252: attempt to index local 'PotionSelected' (a nil value)
[string "@HeroRotation_Druid/Feral.lua"]:252: in function `Condition'
[string "@HeroRotation/Commons.lua"]:94: in function `CastTargetIf'
[string "@HeroRotation_Druid/Feral.lua"]:694: in function <HeroRotation_Druid/Feral.lua:652>
[string "@HeroRotation_Druid/Feral.lua"]:795: in function `?'
[string "@HeroRotation/Main.lua"]:456: in function <HeroRotation/Main.lua:434>

Locals:
TargetUnit = <table> {
 UnitExists = true
 UnitName = "Primal Proto-Whelp"
 UnitNPCID = 193876
 UnitGUID = "Creature-0-3024-2444-12907-193876-0000274E1F"
 UnitID = "target"
 UseCache = true
 UnitCanBeAttacked = true
}
PotionSelected = nil
CombatTime = 6.574000
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Creature-0-3024-2444-12907-193876-0000274E1F"
(*temporary) = "attempt to index local 'PotionSelected' (a nil value)"
Everyone = <table> {
 bool = <function> defined @HeroRotation/Commons.lua:35
 num = <function> defined @HeroRotation/Commons.lua:31
 IsSoloMode = <function> defined @HeroRotation/Commons.lua:72
 CanDoTUnit = <function> defined @HeroRotation/Commons.lua:50
 PotionSelected = <function> defined @HeroRotation/Commons.lua:173
 GroupBuffMissing = <function> defined @HeroRotation/Commons.lua:116
 CastTargetIf = <function> defined @HeroRotation/Commons.lua:93
 UnitIsCycleValid = <function> defined @HeroRotation/Commons.lua:45
 GetCurrentEmpowerData = <function> defined @HeroRotation/Commons.lua:144
 TargetIsValid = <function> defined @HeroRotation/Commons.lua:40
 CastCycle = <function> defined @HeroRotation/Commons.lua:77
 Interrupt = <function> defined @HeroRotation/Commons.lua:55
}
HL = <table> {
 RegisterForEvent = <function> defined @HeroLib/Events/Main.lua:46
 MAXIMUM = 40
 BossFilteredFightRemains = <function> defined @HeroLib/Class/Unit/TimeToDie.lua:385
 Pulse = <function> defined @HeroLib/Main.lua:50
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 PulseInitialized = true
 Druid = <table> {
 }
 Item = <table> {
 }
 CacheHasBeenReset = false
 LiveRealm = <function> defined @HeroLib/Core.lua:34
 RegisterForCombatPrefixEvent = <function> defined @HeroLib/Events/Main.lua:133
 UnregisterForEvent = <function> defined @HeroLib/Events/Main.lua:62
 AddCoreOverride = <function> defined @HeroLib/Misc/Overrides.lua:26
 BetaRealm = <function> defined @HeroLib/Core.lua:44
 Spell = <table> {
 }
 BossFightRemainsIsNotValid = <function> defined @HeroLib/Class/Unit/TimeToDie.lua:370
 GetInstanceInfo = <function> defined @HeroLib/Misc/ToSort.lua:37
 Action = <table> {
 }
 LoadRestores = <function> defined @HeroLib/Misc/Overrides.lua:42
 RegisterForCombatSuffixEvent = <function> defined @HeroLib/Events/Main.lua:148
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 0
 RecoveryTimer = <function> defined @HeroLib/Misc/ToSort.lua:116
 BMPullTime = <function> defined @HeroLib/Misc/ToSort.lua:87
 RegisterForCombatEvent = <function> defined @HeroLib/Events/Main.lua:88
 OutOfCombatTime = <function> defined @HeroLib/Misc/ToSort.lua:82
 UnregisterForSelfCombatEvent = <function> defined @HeroLib/Events/Main.lua:177
 Latency = <function> defined @HeroLib/Misc/ToSort.lua:111
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 GetInstanceDifficulty = <function> defined @HeroLib/Misc/ToSort.lua:72
 LoadOverrides = <function> defined @HeroLib/Misc/Overrides.lua:48
 Print = <function> defined @HeroLib/Core.lua:49
 UnregisterAuraTracking = <function> defined @HeroLib/Events/Aura.lua:37
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 BuildVersion = <function> defined @HeroLib/Core.lua:29
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @HeroLib/Misc/ToSort.lua:77
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 UnregisterForCombatEvent = <function> defined @HeroLib/Events/Main.lua:163
 BossFightR

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment] 2023-10-12 02:56
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/4917c93bc0248c71133b5923fd8f6935d10f93f0

The problem is the PotionSelected() function checks for raid potions, as the addon is technically for max level characters. So when under the usable level for these potions, the potion to use ends up as a nil value. This code change should resolve that issue. Please let me know if you still have a problem after the update.

**Closed as completed** 2023-11-17 13:01 UTC
Labels: Bug
